Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false